language: python
python:
  - "3.6"
  - "3.7"
branches:
  only:
  - master
  - develop
  - /^release-.*$/
install:
  - pip install -r requirements_dev.txt
script:
  - nosetests --with-coverage --cover-package borax
  - flake8 borax tests